# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55820015d9f4d49db9df03222e9fa3a9b0f11594fcd235468261b50b01ebbf947abbcc82bc81914634d8208d99543ee33b0dfa12866bff796b2cbc204b20d40a
  #application_url: user8.masterofcode.com

test:
  secret_key_base: 3df6ef94f640f159ca66819c47ef57ddf2dc992a56de262dfcf07cd6ddd3a3db6460a0588cc442c552ed8727be48c6c6c6d8edeae0463fb601ad9c813cc4dcfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
